-- SITUAÇÃO REAL DOS OFICIAIS - 4º BPM/M
-- Schema mínimo (MySQL / MariaDB)

CREATE TABLE IF NOT EXISTS oficiais (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estado_do_dia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data_ref DATE NOT NULL,
  oficial_id INT NOT NULL,
  situacao VARCHAR(50) NULL,
  observacao VARCHAR(255) NULL,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_estado_oficial FOREIGN KEY (oficial_id) REFERENCES oficiais(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_data_oficial (data_ref, oficial_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DADOS INICIAIS (OFICIAIS) - TUDO EM MAIÚSCULO
INSERT INTO oficiais (nome) VALUES
('TEN CEL PM HELDER ANTONIO DE PAULA'),
('MAJ PM EDUARDO MOSNA XAVIER'),
('MAJ PM ALESSANDRA PAULA TONOLLI'),
('CAP PM CARLOS BORDIM NETO'),
('CAP PM ALBERTO FRANZINI NETO'),
('CAP PM MARCIO SAITO ESSAKI'),
('1º TEN PM DANIEL ALVARES DE SIQUEIRA'),
('1º TEN PM MATEUS PEDRO TEODORO'),
('1º TEN DENT PM FERNANDA BRUNO POMPONIO MARTIGNAGO'),
('1º TEN DENT PM DAYANA DE OLIVEIRA SILVA ALMEIDA'),
('CAP PM ANDRÉ SANTARELLI DE PAULA'),
('CAP PM VINICIO AUGUSTO VOLTARELLI TAVARES'),
('CAP PM JOSE ANTONIO MARCIANO NETO'),
('1º TEN PM IURI FILIPE DOS SANTOS'),
('1º TEN PM ANTÔNIO OVIDIO FERRUCIO CARDOSO'),
('1º TEN PM BRUNO ANTÃO DE OLIVEIRA'),
('1º TEN PM LARISSA AMADEU LEITE'),
('1º TEN PM RENATO FERNANDES FREIRE'),
('1º TEN PM RAPHAEL MECCA SAMPAIO');

-- Observação:
-- Se você já tiver oficiais inseridos, comente o INSERT acima para evitar duplicidade.
