-- SITUAÇÃO REAL DOS OFICIAIS - 4º BPM/M
-- Schema mínimo (MySQL / MariaDB)

CREATE TABLE IF NOT EXISTS oficiais (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS estado_do_dia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  data_ref DATE NOT NULL,
  oficial_id INT NOT NULL,
  situacao VARCHAR(50) NULL,
  observacao VARCHAR(255) NULL,
  atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_estado_oficial FOREIGN KEY (oficial_id) REFERENCES oficiais(id) ON DELETE CASCADE,
  UNIQUE KEY uniq_data_oficial (data_ref, oficial_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- DADOS INICIAIS (OFICIAIS) - TUDO EM MAIÚSCULO
INSERT INTO oficiais (nome) VALUES
('TEN CEL PM HELDER ANTONIO DE PAULA'),
('MAJ PM RICARDO SANTOS MEDEIROS'),
('MAJ PM CARLOS BORDIM NETO'),
('CAP PM MARCIO SAITO ESSAKI'),
('CAP PM JOSE ANTONIO MARCIANO NETO'),
('CAP PM ALBERTO FRANZINI NETO'),
('CAP PM VINICIO AUGUSTO VOLTARELLI TAVARES'),
('CAP PM ANDRE SANTARELLI DE PAULA'),
('CAP PM IURI FILIPE DOS SANTOS'),
('CAP PM MATEUS PEDRO TEODORO'),
('1º TEN PM DANIEL ALVES DE SIQUEIRA'),
('1º TEN DENT PM FERNANDA BRUNO POMPONIO MARTIGNAGO'),
('1º TEN DENT PM DAYANA DE OLIVEIRA SILVA ALMEIDA'),
('1º TEN PM ANTONIO OVIDIO FERRUCIO CARDOSO'),
('1º TEN PM BRUNO ANTAO DE OLIVEIRA'),
('1º TEN PM LARISSA AMADEU LEITE'),
('1º TEN PM RENATO FERNANDES FREIRE'),
('1º TEN PM RAPHAEL MECCA SAMPAIO'),
('ASP OF PM JOSE SEBASTIAO DOS SANTOS NETO'),
('ASP OF PM LENISE HELENA TRAGANTE DE SOUZA CRISTO');

-- Observação:
-- Se você já tiver oficiais inseridos, comente o INSERT acima para evitar duplicidade.
